
name: Build Executable for Windows/MacOS/Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    
      # Check-out repository
      - uses: actions/checkout@v3
      
      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          access-token: ${{ secrets.NUITKA_COMMERCIAL_ACCESS_TOKEN }}
          standalone: true
          onefile: false
          show-scons: false
          enable-plugins: pyside6
          # include-package-data: qt_material
          # include-data-dir: ./images=./images,./resources=./resources
          enable-console: false
          disable-console: true
          # Windows specific controls
          # windows-icon-from-ico: ./resources/app.ico
          windows-uac-admin: false
          windows-uac-uiaccess: false
          windows-company-name: UNDO
          # Macos specific controls
          macos-create-app-bundle: true
          # macos-app-icon: ./resources/app.ico
          macos-app-version: 1.0
          
      - name: Compress to ZIP for Windows & Linux
        if: ${{ runner.os == 'Windows' || runner.os == 'Linux' }}
        run: |
          7z a build/main_${{ runner.os }}.zip ./build/main.dist/*
          
      - name: Compress to ZIP for Macos
        if: ${{ runner.os == 'macOS' }}
        run: |
          7z a build/main_${{ runner.os }}.zip ./build/main.app/          
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.zip
            
